apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myApp
  namespace: dev
spec:
  source:
    repoURL: "https://github.com/Oronano/Kubernetes.git"
    path: "."
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true